# Please see the docs for configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    allow:
      # Only direct dependencies, skip indirect deps in the lockfile
      - dependency-type: 'direct'
    ignore:
      # Major Node version updates will be done manually
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
