name: Publish Package
on:
  issue_comment:
    types:
      - created
jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      ref: ${{ steps.pull-request-branch.outputs.head_ref }}
      sha: ${{ steps.pull-request-branch.outputs.head_sha }}
    # Only run on a specific pull request comment
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'publish this please')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: pull-request-branch
  publish:
    needs:
      - setup
    uses: ./.github/workflows/workflow-publish.yml
    with:
      ref: ${{ needs.setup.outputs.ref }}
      version: 0.0.0-${{ needs.setup.outputs.sha }}
      pull-request-number: ${{ github.event.issue.number }}
    secrets: inherit
