name: Publish Package
on:
  issue_comment:
    types:
      - created
jobs:
  publish-package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
      pull-requests: write
    # Only run for comments on pull requests
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'publish this please')
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          scope: '@tstapleton'
          registry-url: 'https://npm.pkg.github.com'
      - name: Create yarnrc.yml
        run: |
          cat >> ./.yarnrc.yml <<EOF
          npmAuthToken: "$NODE_AUTH_TOKEN"
          npmScopes:
            tstapleton:
              npmPublishRegistry: "https://npm.pkg.github.com"
              npmAlwaysAuth: true
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: yarn version 0.0.0-${{ steps.comment-branch.outputs.head_ref }} && yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Install the package by running:
                \`\`\`
                yarn add --dev @tstapleton/pirate-quote@0.0.0-${{ steps.comment-branch.outputs.head_ref }}
                \`\`\`
                Happy coding! 📦 🚀
              `
            })
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: publish
          hide_and_recreate: true
          hide_classify: OUTDATED
          message: |
            Install the package by running:
            ```
            yarn add --dev @tstapleton/pirate-quote@0.0.0-${{ steps.comment-branch.outputs.head_ref }}
            ```
            Happy coding! 📦 🚀
