name: Main
on:
  push:
    branches:
      - main
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # yarn versions needs more git history
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create yarnrc.yml
        run: |
          cat >> ./.yarnrc.yml <<EOF
          npmAuthToken: "$NODE_AUTH_TOKEN"
          npmScopes:
            tstapleton:
              npmPublishRegistry: "https://npm.pkg.github.com"
              npmAlwaysAuth: true
          EOF
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci
      - name: Archive code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/report.json
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        with:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Publish package
        run: yarn version patch && yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
