name: Main Build
on:
  push:
    branches:
      - main
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci
      - name: Push tag for new package version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          DEFAULT_BUMP: patch
          # Fine-grained token GHA pirate-quote push tag expires 2023-10-23
          GITHUB_TOKEN: ${{ secrets.PAT_PUSH_TAG }}
          WITH_V: true
