name: Main
on:
  push:
    branches:
      - main
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci
      - name: Archive code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/report.json
      - name: Push tag for new package version
        uses: anothrNick/github-tag-action@1.61.0
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
