name: Pull Request Build
on:
  pull_request:
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          branch: main
          name: code-coverage-report
          path: coverage/base
      - name: Report test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          base-coverage-file: coverage/base/report.json
          coverage-file: coverage/report.json
          skip-step: all

  # Used as the required status check on PRs so a failure prevents a merge
  build-result:
    runs-on: ubuntu-latest
    permissions: {}
    needs:
      - build
    if: ${{ always() }}
    steps:
      # If any of the needed jobs fail or are cancelled then fail this job
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
