name: Pull Request Build
on:
  pull_request:
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci

  # Used as the required status check on PRs so a failure prevents a merge
  build-result:
    runs-on: ubuntu-latest
    permissions: {}
    needs:
      - build
    if: ${{ always() }}
    steps:
      # If any of the needed jobs fail or are cancelled then fail this job
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1
