name: Pull Requests
on:
  pull_request:
# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # yarn versions needs more git history
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          scope: '@tstapleton'
          registry-url: 'https://npm.pkg.github.com'
      - name: Build package
        run: yarn build
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test:ci
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          branch: main
          name: code-coverage-report
          path: coverage/base
      - name: Report test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          annotations: none
          base-coverage-file: coverage/base/report.json
          coverage-file: coverage/report.json
          skip-step: all
